on:
  push:
    branches:
      - '*'
      - '!main'
  pull_request:
    types:
      - opened
      - reopened
      - closed
      - synchronize


jobs:
  upload_tf_vars:
    name: 'Upload tfvars to Artifact'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extra Variables
        run: |
          echo '"github_repository_name": "Just-Right-Cloud/argo-cd",' >> test.tfvars.json
          echo '"github_application_id": "${{ vars.ARGOCD_APP_ID }}",' >> test.tfvars.json
          echo '"github_application_installation_id": "${{ vars.ARGOCD_APP_INSTALLATION_ID }}",' >> test.tfvars.json
          echo '"github_application_private_key": "${{ vars.ARGOCD_APP_PRIVATE_KEY }}"' >> test.tfvars.json

      - name: Upload tfvars
        uses: actions/upload-artifact@v4
        with:
          name: tfvars
          path: 'test.tfvars.json'

  test:
    if: github.repository != 'Tanchwa/infrastructure-deployment-template'
    name: 'Terraform Test'
    uses: Tanchwa/workflows-terraform-deployment/.github/workflows/terraform_test.yaml@main
    needs: upload_tf_vars
    secrets: 
      GOOGLE_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
      GOOGLE_STATE_BUCKET: ${{ secrets.GOOGLE_STATE_BUCKET }}
      INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      terraform_version: "1.12"
      working_directory: "."
      test_level: "integration"
      tf_vars_artifact: "tfvars"
      tf_vars_filename: "test.tfvars.json"
      environment: "test"

  plan:
    if: (github.event.pull_request.merged && github.base_ref == 'main') && github.repository != 'Tanchwa/infrastructure-deployment-template'
    name: 'Terraform Plan'
    uses: Tanchwa/workflows-terraform-deployment/.github/workflows/terraform_plan.yaml@main
    needs: upload_tf_vars
    secrets: 
      GOOGLE_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
      GOOGLE_STATE_BUCKET: ${{ secrets.GOOGLE_STATE_BUCKET }}
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      terraform_version: "1.12"
      working_directory: "."
      tf_vars_artifact: "tfvars"
      tf_vars_filename: "test.tfvars.json"
      environment: "test"

  apply:
    if: (github.event.pull_request.merged && github.base_ref == 'main') && github.repository != 'Tanchwa/infrastructure-deployment-template'
    needs:
      - plan
      - upload_tf_vars
    name: 'Terraform Apply'
    uses: Tanchwa/workflows-terraform-deployment/.github/workflows/terraform_apply.yaml@main
    secrets:
      GOOGLE_WORKLOAD_IDENTITY_PROVIDER: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
      GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
      GOOGLE_STATE_BUCKET: ${{ secrets.GOOGLE_STATE_BUCKET }}
    permissions:
      contents: read
      pull-requests: write
      id-token: write
    with:
      terraform_version: "1.12"
      working_directory: "."
      tf_vars_artifact: "tfvars"
      tf_vars_filename: "test.tfvars.json"
      environment: "test"
